Use BSCANE2 tap for FPGA interaction
This commit uses the `bscane_tap` from the `riscv-dbg` module to
faciliate debugging with OpenOCD.

The TAP is correctly identified on the VCU128 but the debugger is not
able to halt the core. Imho, this is due to the missing bootrom which
will just hang the FPGA.

Unfortunately, using the BSCANE2 primitives has the drawback of that the
Xilinx HW Server can not be connected at the same time (resource
conflict on the USB interface). That in turn means, that debugging with
GDB and ILA is mutual exclusive.

That is the current output I can produce with `OpenOCD` when connecting:

```
~$ openocd -f vcu128.cfg

Open On-Chip Debugger 0.11.0+dev-00117-gab337d05f-dirty
(2021-04-28-09:46)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter speed' not 'adapter_khz'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 100 kHz
Info : JTAG tap: riscv.cpu tap/device found: 0x14b79093 (mfg: 0x049
(Xilinx), part: 0x4b79, ver:
0x1)
Info : datacount=2 progbufsize=8
Error: unable to halt hart 0
Error:   dmcontrol=0x80000001
Error:   dmstatus =0x00000c82
Error: Fatal: Hart 0 failed to halt during examine()
Warn : target riscv.cpu examination failed
Info : starting gdb server for riscv.cpu on 3333
Info : Listening on port 3333 for gdb connections
```